pipeline:
  identifier: Build_Ravitejaganji1234_ssit_loki_frontend_module_1740119577212
  name: Build ssit-loki-frontend-module
  orgIdentifier: default
  projectIdentifier: Practice
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1740116914085
        repoName: Ravitejaganji1234/ssit-loki-frontend-module
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
